### ISSUE TITLE
User with no articles causes failure

### ISSUE THREAD

**Issue by yermilov** [potic/potic-aggregator#19]
![image](https://user-images.githubusercontent.com/1258970/32355534-ef02ba86-c037-11e7-9d3f-c379a67475e7.png)

**Comment by yermilov** [comment]
`23:21:43.313 [http-nio-8080-exec-4] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: request for /user/me/section failed: java.util.NoSuchElementException] with root cause
java.util.NoSuchElementException: Cannot access last() element from an empty List
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.last(DefaultGroovyMethods.java:8913)
        at org.codehaus.groovy.runtime.dgm$382.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at me.potic.aggregator.service.LatestSectionService.fetchChunk(LatestSectionService.groovy:30)
        at me.potic.aggregator.service.LatestSectionService$fetchChunk$0.callCurrent(Unknown Source)
        at me.potic.aggregator.service.LatestSectionService.fetchSectionHead(LatestSectionService.groovy:23)
        at me.potic.aggregator.service.LatestSectionService$$FastClassBySpringCGLIB$$f42baa0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669)
        at me.potic.aggregator.service.LatestSectionService$$EnhancerBySpringCGLIB$$ccc218f.fetchSectionHead(<generated>)
        at me.potic.aggregator.service.LatestSectionService$fetchSectionHead.call(Unknown Source)
        at me.potic.aggregator.controller.SectionsController$_userSections_closure1$_closure2.doCall(SectionsController.groovy:42)
        at me.potic.aggregator.controller.SectionsController$_userSections_closure1$_closure2.doCall(SectionsController.groovy)
        at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at groovyx.gpars.GParsPool$MyCancellableRecursiveTask.compute(GParsPool.groovy:249)
        at jsr166y.RecursiveTask.exec(RecursiveTask.java:64)
        at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
        at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
        at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
        at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
        at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)`
